### ISSUE TITLE
Remove "Rob Bye"

### ISSUE THREAD

**Issue by cassidyjames** [elementary/wallpapers#125]
I'm not feeling it as much as the other wallpapers. It's kind of muted, it maxes out below 4K, it's pretty soft, and it has people in it. As we add more wallpapers, I think it's one of the weaker ones that could go.

![Screenshot from 2020-10-01 21-51-30@2x](https://user-images.githubusercontent.com/611168/94886525-a3eb9a00-0430-11eb-8147-6e7a94e4e104.png)

**Comment by danrabbit** [comment]
Yeah do it

**Comment by anthhov** [comment]
Came here from DuckDuckGo search engine.

Guys, I believe this issue was created by mistake.
We all know that **Rob Bye** was and still is the best wallpaper of all times!
