### ISSUE TITLE
Transparent panel on the top look less beautiful

### ISSUE THREAD

**Issue by nardiyansah** [elementary/wallpapers#131]
Hi I'm nardiyansah from Indonesia. I've been using elementary for several months and today I find transparent look less beautiful in some wallpaper. I just want to tell you about it. 

this is some wallpaper I found.
![up_indicator](https://user-images.githubusercontent.com/41910581/95877403-447d7a80-0d9e-11eb-97a5-e9cf4259aa1e.png)
![Screenshot from 2020-10-13 21 52 47](https://user-images.githubusercontent.com/41910581/95877590-77c00980-0d9e-11eb-8d35-e0e74043b26e.png)
![Screenshot from 2020-10-13 21 54 04](https://user-images.githubusercontent.com/41910581/95877789-af2eb600-0d9e-11eb-921e-8c5dea849f04.png)
![Screenshot from 2020-10-13 21 54 58](https://user-images.githubusercontent.com/41910581/95877850-c2da1c80-0d9e-11eb-9979-88d7b7862998.png)

**Comment by danrabbit** [comment]
Judging by the look of the dock, I'm guessing you're probably using a non-standard system stylesheet. It is expected to run into these kinds of errors when making modifications to the system.

Closing as "out of scope" since the panel does not appear this way with the default system stylesheet
