### ISSUE TITLE
Remove proprietary files

### ISSUE THREAD

**Issue by throwaway1037** [elementary/wallpapers#137]
The Unsplash and Pexels licenses are [nonfree](https://freedomdefined.org). I propose instating the rule that all works must be free.

**Comment by danrabbit** [comment]
The only conditions on the Unsplash license are that you cannot redistribute a mass collection of their images as a direct competitor. In other words, you can't download all of the Unsplash library and start a website called "Resplash" hosting them. Otherwise, as a non-competitor, you are free to download, redistribute, remix etc. For the purposes of elementary and for the purposes of elementary users, these images are effectively free. I don't think this is an unfair restriction

**Comment by cassidyjames** [comment]
To further clarify, we've been in contact with Unsplash and their legal team to encourage them to make this abundantly clear on their website, but: the works as released in this repository _are_ completely free to use. elementary had to agree to the terms of the Unsplash license _when **we** downloaded them_ but we are free to redistribute them here, and end users have every freedom to use the wallpapers however they would please from elementary OS.

**Comment by throwaway1037** [comment]
> The only conditions on the Unsplash license are that you cannot redistribute a mass collection of their images as a direct competitor. In other words, you can't download all of the Unsplash library and start a website called "Resplash" hosting them.

Hence, the images are proprietary.

> Otherwise, as a non-competitor, you are free to download, redistribute, remix etc. For the purposes of elementary and for the purposes of elementary users, these images are effectively free. I don't think this is an unfair restriction

It is irrelevant whether you view these as "unfair restriction"s. Moreover, "effectively free" is not good enough.

It is not up to the Elementary team to write the [definition](https://freedomdefined.org) of freedom as it applies to works.

If Elementary truly stands for freedom, the nonfree images must be removed.

> To further clarify, we've been in contact with Unsplash and their legal team to encourage them to make this abundantly clear on their website, but: the works as released in this repository _are_ completely free to use.

"free to use" is not good enough; the images are still proprietary.

> elementary had to agree to the terms of the Unsplash license _when **we** downloaded them_

Just to clarify myself, I am not suggesting that Elementary violated the license, just that they must not accept proprietary works into their packages.

> but we are free to redistribute them here, and end users have every freedom to use the wallpapers however they would please from elementary OS.

Except they do not have the freedom to make an image hosting service. That license is extremely anti-competitive and anti-social. It is against part of what freedom stands for: the proliferation of ideas and the sharing of human knowledge.

A practical ramification of their proprietary license is that Wikipedia and the other Wikimedia Foundation projects cannot use any works licensed under it. Wikimedia Commons could be classed as a "competing service". As a result, the entirety of the huge collection of images licensed under the proprietary Unsplash license cannot be included in Wikiepdia articles, the sole purpose of which is to allow people to share human knowledge in freedom.

**Comment by jtagcat** [comment]
Read both previous comments again.

**Comment by throwaway1037** [comment]
What would re-reading the comments achieve?

As a result of discovering that these files are proprietary, this will probably result in at least one distribution, [Parabola](https://parabola.nu), either removing the package of these image from their repositories, or forking it to make a cleaned-up version of the package, consisting of only the free images.

There are a wealth of free images available online. Would it not be a good compromise to use some of those instead? Wikimedia Commons has tons of beautiful images which could be used as wallpapers, for example.

**Comment by cassidyjames** [comment]
No new information has been presented here, and posting lengthy diatribes on our issue tracker from a literal throwaway account is a waste of everyone’s time. You're free to use the images in this repository, or not.
