### ISSUE TITLE
Define a new minimum wallpaper size

### ISSUE THREAD

**Issue by danrabbit** [elementary/wallpapers#14]
HiDPI is now a thing and most of the wallpapers we're shipping are scaled down. I think we need to define a new minimum size that sits closer to 4K

**Comment by danrabbit** [comment]
@elementary/ux

**Comment by cassidyjames** [comment]
Possibly for any new walls, yeah. 3200×1800 is the minimum I'd go with since that's pretty common on 13" displays, but 3840×2160 isn't a bad size either ("4K" on most 15"+ displays).
