### ISSUE TITLE
Upgrading package from 6.0.0 to 6.1.0 breaks greeter in elementary OS 5.1

### ISSUE THREAD

**Issue by marmeladapk** [elementary/wallpapers#167]
### What Happened?

Upgrading package from 6.0.0 to 6.1.0 breaks greeter in elementary OS 5.1. I noticed it on one of my systems, then on the other, also running 5.1, I installed all updates except wallpapers. Rebooted, greeter was fine. Upgraded wallpapers, rebooted, greeter was borked (in the same way as in [this reddit post](https://www.reddit.com/r/elementaryos/comments/rgoudl/after_updates_some_time_ago_this_happened/)).

Installing wallpapers from source fixes this issue (with `ninja install`).

I noticed, that `ninja install` added files and one link in `/usr/share/backgrounds` that weren't there after upgrading package.

I suspect that https://github.com/elementary/wallpapers/commit/d1781a5048f6fc52c4822db25b05b8ceadb19402 is the culprit, as it is the only difference between 6.0 and 6.1 in deb packaging, and installing from source seems fine, but without building deb package I can't verify that.

This happended on two systems that were running 5.1.

### Steps to Reproduce

Upgrade package from 6.0.0 to 6.1.0 in elementary OS 5.1.

### Expected Behavior

Upgrading package from 6.0.0 to 6.1.0 does not break greeter in elementary OS 5.1.

### OS Version

5.x (Hera)

### Software Version

Latest release (I have run all updates)

**Comment by danrabbit** [comment]
Ah yep there was a packaging error here. A fix is being built now. Sorry for the inconvenience!

**Comment by marmeladapk** [comment]
Fix fixed the issue. Thanks!
