### ISSUE TITLE
New Wallpaper for OS 8

### ISSUE THREAD

**Issue by danirabbit** [elementary/wallpapers#183]
We need a new default for OS 8 :)

**Comment by 1280px** [comment]
What about the bridge wallpaper (or [similar](https://github.com/elementary/wallpapers/pull/170#issuecomment-1537510970)) from #170?

**Comment by danirabbit** [comment]
@1280px feel free to open new pull requests if you have proposals. #170 was closed because it didn't seem like anyone had the time/interest to edit it
