### ISSUE TITLE
Picture selection (list format) must choose "Open"

### ISSUE THREAD

**Issue by bksubhuti** [elementary/wallpapers#22]
When selecting a picture under "custom", one must select "open" when there is nothing selected to get a thumbnail view.
This should default to thumbnail view from the beginning.  
"Open" should be renamed to "Set Wallpaper" when a picture is selected.  
It should be grey if nothing is selected.
Double clicking should select and set and close the dialog.

**Comment by danrabbit** [comment]
This repository is a collection of wallpapers. I think you're looking for https://github.com/elementary/switchboard-plug-pantheon-shell/issues

Closing as "invalid" for this tracking
