### ISSUE TITLE
Idea: Unsplash search for wallpaper images

### ISSUE THREAD

**Issue by marizmelo** [elementary/wallpapers#36]
I would love to be able to search the unspalsh open API (https://unsplash.com/developers) for images to be used as my wallpaper in eOS.

**Comment by lewisgoddard** [comment]
This might be a duplicate of elementary/switchboard-plug-pantheon-shell#32 as that is were this would actually be implemented (I think).

**Comment by marizmelo** [comment]
Thank you @lewisgoddard, closing this issue.
