### ISSUE TITLE
clarify which content licenses are OK

### ISSUE THREAD

**Issue by decathorpe** [elementary/wallpapers#41]
At the moment, the allowed content is vaguely defined as "openly-licensed and okay for commercial use". It probably would be helpful to define this more clearly.

For example, fedora has a comprehensive list of "good" and "bad" licenses for content that isn't in the Public Domain, available at <https://fedoraproject.org/wiki/Licensing:Main#Content_Licenses>.

**Comment by decathorpe** [comment]
Ping?

**Comment by cassidyjames** [comment]
@decathorpe right now all wallpapers are public domain, so that's the only case we're dealing with. Why do you need a "comprehensive list" of acceptable licenses when all photos are licensed under the same license, and they're attributed in the repository?

**Comment by decathorpe** [comment]
@cassidyjames I opened this issue because @danrabbit asked me to, IIRC. At that point in time, images that weren't in the public domain were still part of the repo.

But yes, if you will only accept public domain works going forward, this issue is "resolved".

**Comment by cassidyjames** [comment]
@decathorpe I also added some specifically-acceptable licenses to the README.

**Comment by decathorpe** [comment]
@cassidyjames ok, I did not notice that. Sounds good to me.
