### ISSUE TITLE
automatic install script missing

### ISSUE THREAD

**Issue by decathorpe** [elementary/wallpapers#6]
A small script installing the wallpapers system-wide (to `/usr/share/backgrounds/elementary` or something like that) would be appreciated, so no manual copying of the files has to be done (a similar, convenient script is often included with icon themes and GTK themes).

I think a simple CMake solution would be preferable for an elementary project, though.

**Comment by codygarver** [comment]
I oppose this because it's overkill, installing wallpapers is copying and pasting, which should be easy enough for packagers already.
