### ISSUE TITLE
White pixel in upper right quadrant of Ashim DSilva photo

### ISSUE THREAD

**Issue by PretzelJones** [elementary/wallpapers#62]
There is a single white pixel in upper right quadrant of Ashim DSilva photo. I have corrected it and posted the new image here: https://drive.google.com/open?id=1icmoyBGAk0JsdUSy8FZvPiLkyNIhcMQh

I know this isn't the proper way. I know I should submit a pull request and push the fix to the master branch, but I'm new to git and don't want to jack anything up :)

**Comment by davidmhewitt** [comment]
Fixed in #66
