### ISSUE TITLE
Request permission from author bo0xvn for upstreams to distribute his wallpapers too

### ISSUE THREAD

**Issue by codygarver** [elementary/wallpapers#7]
bo0xvn was kind enough to give us permission to distribute his wallpapers. Now upstreams are trying to package our wallpapers and asking for more permission from bo0xvn would help resolve some licensing issues.

**Comment by Conan-Kudo** [comment]
It'd be preferred to be under CC-BY-SA license, but CC-BY or CC-BY-SA-ND is fine too. See [Fedora's page on good content licenses for more info](https://fedoraproject.org/wiki/Licensing:Main#Content_Licenses). These are pretty much in line with how distributions need the content to be licensed.
